{"name": "test_login_A_1___login001____登录成功测试____19111111116____123456____登录成功____p1__", "status": "failed", "statusDetails": {"message": "AssertionError: '登录成功' != '未知错误'\n- 登录成功\n+ 未知错误", "trace": "self = <test_login.Test_Login_A testMethod=test_login_A_1___login001____登录成功测试____19111111116____123456____登录成功____p1__>\naa = ['login001', '登录成功测试', '19111111116', '123456', '登录成功', 'p1']\n\n    @data(*ddata)\n    def test_login_A(self,aa):\n        #print('传入的值：',aa)\n        self.data['phone']=aa[2]\n        self.data['password'] = aa[3]\n        #发送请求\n        r=requests.post(url=self.url,data=self.data)\n        r=json.loads(r.text)\n        #print('响应结果：',r)\n        #断言\n>       self.assertEqual(aa[4],r['msg'])\nE       AssertionError: '登录成功' != '未知错误'\nE       - 登录成功\nE       + 未知错误\n\ntest_login.py:33: AssertionError"}, "start": 1685314016024, "stop": 1685314016163, "uuid": "d48b1eb0-b1f0-4cbf-a65e-14bb3222951f", "historyId": "798b770e0b756ac51bd6eacc43fbaa0c", "testCaseId": "65a7b538fbd0f70be870eff6d58b3808", "fullName": "test_case.test_login.Test_Login_A#test_login_A_1___login001____登录成功测试____19111111116____123456____登录成功____p1__", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login_A"}, {"name": "host", "value": "DESKTOP-OH19PGP"}, {"name": "thread", "value": "12840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login"}]}